### ISSUE TITLE
Missing of dataset

### ISSUE THREAD

**Issue by SibiK-AI** [albertszg/DFAWnet#1]
In running the program you have arranged all the datasets in a particular order in a directory.
It will be useful  if you upload the actual dataset  folder

**Comment by albertszg** [comment]
I'm sorry, this library does not provide specific data due to its large size. For XJTU-SY, CWRU and MFPT dataset, their file structure has not changed, and the corresponding references are also provided in the paper. You can download the corresponding data directly from the source website.
