### ISSUE TITLE
请问数据集可以在什么地方下载，目前只有西储大学的是开放的

### ISSUE THREAD

**Issue by laocaifeng6688** [albertszg/DFAWnet#2]

**Comment by albertszg** [comment]
CWRU：https://engineering.case.edu/bearingdatacenter/download-data-file
MFPT: https://mfpt.org/fault-data-sets/
XJTU-SY: https://github.com/WangBiaoXJTU/xjtu-sy-bearing-datasets

**Comment by albertszg** [comment]
HYFJ is a private data set and is not publicly available
